// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// API Overview:
///
/// The `beyondcorp.googleapis.com` service implements the Google Cloud
/// BeyondCorp API.
///
/// Data Model:
///
/// The AppConnectionsService exposes the following resources:
///
/// * AppConnections, named as follows:
///   `projects/{project_id}/locations/{location_id}/appConnections/{app_connection_id}`.
///
/// The AppConnectionsService service provides methods to manage
/// (create/read/update/delete) BeyondCorp AppConnections.
///
/// @Snippet(path: "AppConnectionsServiceQuickstart")
public final class AppConnectionsServiceClient: Clients.AppConnectionsServiceProtocol, Sendable {
  let inner: any Clients.AppConnectionsServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AppConnectionsServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AppConnectionsServiceStub = try Clients.AppConnectionsServiceTransport(
      options)
    inner = Clients.AppConnectionsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AppConnectionsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists AppConnections in a given project and location.
  ///
  /// @Snippet(path: "AppConnectionsService_ListAppConnections")
  public func listAppConnections(
    request: ListAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ListAppConnectionsResponse {
    try await self.inner.listAppConnections(request: request, options: options)
  }

  /// Gets details of a single AppConnection.
  ///
  /// @Snippet(path: "AppConnectionsService_GetAppConnection")
  public func getAppConnection(
    request: GetAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.AppConnection {
    try await self.inner.getAppConnection(request: request, options: options)
  }

  /// Creates a new AppConnection in a given project and location.
  ///
  /// @Snippet(path: "AppConnectionsService_CreateAppConnection")
  public func createAppConnection(
    request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAppConnection(request: request, options: options)
  }

  /// Creates a new AppConnection in a given project and location.
  ///
  /// @Snippet(path: "AppConnectionsService_CreateAppConnection")
  public func createAppConnectionPollingUntilDone(
    request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      return try op._extractStatus(AppConnection.self)
    }
    let rawOp = try await self.createAppConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single AppConnection.
  ///
  /// @Snippet(path: "AppConnectionsService_UpdateAppConnection")
  public func updateAppConnection(
    request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAppConnection(request: request, options: options)
  }

  /// Updates the parameters of a single AppConnection.
  ///
  /// @Snippet(path: "AppConnectionsService_UpdateAppConnection")
  public func updateAppConnectionPollingUntilDone(
    request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      return try op._extractStatus(AppConnection.self)
    }
    let rawOp = try await self.updateAppConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single AppConnection.
  ///
  /// @Snippet(path: "AppConnectionsService_DeleteAppConnection")
  public func deleteAppConnection(
    request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAppConnection(request: request, options: options)
  }

  /// Deletes a single AppConnection.
  ///
  /// @Snippet(path: "AppConnectionsService_DeleteAppConnection")
  public func deleteAppConnectionPollingUntilDone(
    request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAppConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resolves AppConnections details for a given AppConnector.
  /// An internal method called by a connector to find AppConnections to connect
  /// to.
  ///
  /// @Snippet(path: "AppConnectionsService_ResolveAppConnections")
  public func resolveAppConnections(
    request: ResolveAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ResolveAppConnectionsResponse {
    try await self.inner.resolveAppConnections(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppConnectionsService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AppConnectionsService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "AppConnectionsService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "AppConnectionsService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "AppConnectionsService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectionsService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectionsService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectionsService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectionsService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AppConnectionsServiceClient`.
  ///
  /// To mock `AppConnectionsServiceClient` change your functions to receive
  /// `some AppConnectionsServiceProtocol` or `any AppConnectionsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AppConnectionsServiceProtocol: Sendable {
    /// See `AppConnectionsServiceClient.createAppConnection`.
    func createAppConnectionPollingUntilDone(request: CreateAppConnectionRequest) async throws
      -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.createAppConnection`.
    func createAppConnectionPollingUntilDone(
      parent: Swift.String,
      appConnection: AppConnection?,
      appConnectionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.updateAppConnection`.
    func updateAppConnectionPollingUntilDone(request: UpdateAppConnectionRequest) async throws
      -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.updateAppConnection`.
    func updateAppConnectionPollingUntilDone(
      appConnection: AppConnection?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.deleteAppConnection`.
    func deleteAppConnectionPollingUntilDone(request: DeleteAppConnectionRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppConnectionsServiceClient.deleteAppConnection`.
    func deleteAppConnectionPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppConnectionsServiceClient.listAppConnections`.
    func listAppConnections(
      request: ListAppConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ListAppConnectionsResponse

    /// See `AppConnectionsServiceClient.getAppConnection`.
    func getAppConnection(
      request: GetAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.AppConnection

    /// See `AppConnectionsServiceClient.createAppConnection`.
    func createAppConnection(
      request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectionsServiceClient.createAppConnection`.
    func createAppConnectionPollingUntilDone(
      request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.updateAppConnection`.
    func updateAppConnection(
      request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectionsServiceClient.updateAppConnection`.
    func updateAppConnectionPollingUntilDone(
      request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppConnection>

    /// See `AppConnectionsServiceClient.deleteAppConnection`.
    func deleteAppConnection(
      request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectionsServiceClient.deleteAppConnection`.
    func deleteAppConnectionPollingUntilDone(
      request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppConnectionsServiceClient.resolveAppConnections`.
    func resolveAppConnections(
      request: ResolveAppConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ResolveAppConnectionsResponse

    /// See `AppConnectionsServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppConnectionsServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AppConnectionsServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppConnectionsServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppConnectionsServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppConnectionsServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AppConnectionsServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AppConnectionsServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AppConnectionsServiceProtocol {
  public func listAppConnections(request: ListAppConnectionsRequest) async throws
    -> GoogleCloudBeyondCorpAppConnectionsV1.ListAppConnectionsResponse
  {
    try await self.listAppConnections(request: request, options: .init())
  }

  public func listAppConnections(
    request: ListAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ListAppConnectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAppConnectionsByItems(
    request: ListAppConnectionsRequest
  ) -> any AsyncSequence<AppConnection, Swift.Error> & Sendable {
    self.listAppConnectionsByItems(request: request, options: .init())
  }

  /// Lists AppConnections in a given project and location.
  ///
  /// @Snippet(path: "AppConnectionsService_ListAppConnections")
  public func listAppConnectionsByItems(
    request: ListAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AppConnection, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBeyondCorpAppConnectionsV1.ListAppConnectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listAppConnections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAppConnectionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<AppConnection, Swift.Error> & Sendable {
    let request = ListAppConnectionsRequest().with {
      $0.parent = parent
    }
    return self.listAppConnectionsByItems(request: request)
  }

  public func getAppConnection(request: GetAppConnectionRequest) async throws
    -> GoogleCloudBeyondCorpAppConnectionsV1.AppConnection
  {
    try await self.getAppConnection(request: request, options: .init())
  }

  public func getAppConnection(
    request: GetAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.AppConnection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAppConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.AppConnection {
    let request = GetAppConnectionRequest().with {
      $0.name = name
    }
    return try await self.getAppConnection(request: request)
  }

  public func createAppConnection(request: CreateAppConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAppConnection(request: request, options: .init())
  }

  public func createAppConnection(
    request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAppConnectionPollingUntilDone(request: CreateAppConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<AppConnection>
  {
    try await self.createAppConnectionPollingUntilDone(request: request, options: .init())
  }

  public func createAppConnectionPollingUntilDone(
    request: CreateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAppConnectionPollingUntilDone(
    parent: Swift.String,
    appConnection: AppConnection?,
    appConnectionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let request = CreateAppConnectionRequest().with {
      $0.parent = parent
      $0.appConnection = appConnection
      $0.appConnectionId = appConnectionId
    }
    return try await self.createAppConnectionPollingUntilDone(request: request)
  }

  public func updateAppConnection(request: UpdateAppConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAppConnection(request: request, options: .init())
  }

  public func updateAppConnection(
    request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAppConnectionPollingUntilDone(request: UpdateAppConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<AppConnection>
  {
    try await self.updateAppConnectionPollingUntilDone(request: request, options: .init())
  }

  public func updateAppConnectionPollingUntilDone(
    request: UpdateAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAppConnectionPollingUntilDone(
    appConnection: AppConnection?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AppConnection> {
    let request = UpdateAppConnectionRequest().with {
      $0.appConnection = appConnection
      $0.updateMask = updateMask
    }
    return try await self.updateAppConnectionPollingUntilDone(request: request)
  }

  public func deleteAppConnection(request: DeleteAppConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAppConnection(request: request, options: .init())
  }

  public func deleteAppConnection(
    request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAppConnectionPollingUntilDone(request: DeleteAppConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAppConnectionPollingUntilDone(request: request, options: .init())
  }

  public func deleteAppConnectionPollingUntilDone(
    request: DeleteAppConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAppConnectionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAppConnectionRequest().with {
      $0.name = name
    }
    return try await self.deleteAppConnectionPollingUntilDone(request: request)
  }

  public func resolveAppConnections(request: ResolveAppConnectionsRequest) async throws
    -> GoogleCloudBeyondCorpAppConnectionsV1.ResolveAppConnectionsResponse
  {
    try await self.resolveAppConnections(request: request, options: .init())
  }

  public func resolveAppConnections(
    request: ResolveAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectionsV1.ResolveAppConnectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resolveAppConnectionsByItems(
    request: ResolveAppConnectionsRequest
  ) -> any AsyncSequence<ResolveAppConnectionsResponse.AppConnectionDetails, Swift.Error> & Sendable
  {
    self.resolveAppConnectionsByItems(request: request, options: .init())
  }

  /// Resolves AppConnections details for a given AppConnector.
  /// An internal method called by a connector to find AppConnections to connect
  /// to.
  ///
  /// @Snippet(path: "AppConnectionsService_ResolveAppConnections")
  public func resolveAppConnectionsByItems(
    request: ResolveAppConnectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ResolveAppConnectionsResponse.AppConnectionDetails, Swift.Error> & Sendable
  {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBeyondCorpAppConnectionsV1.ResolveAppConnectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.resolveAppConnections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func resolveAppConnectionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ResolveAppConnectionsResponse.AppConnectionDetails, Swift.Error> & Sendable
  {
    let request = ResolveAppConnectionsRequest().with {
      $0.parent = parent
    }
    return self.resolveAppConnectionsByItems(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppConnectionsService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectionsService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
