// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for BeyondCorp.ResolveAppConnections.
public struct ResolveAppConnectionsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// A list of BeyondCorp AppConnections with details in the project.
  public var appConnectionDetails: [ResolveAppConnectionsResponse.AppConnectionDetails] = []

  /// A token to retrieve the next page of results, or empty if there are no more
  /// results in the list.
  public var nextPageToken: Swift.String = Swift.String()

  /// A list of locations that could not be reached.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ResolveAppConnectionsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResolveAppConnectionsResponse().with { $0.appConnectionDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details of the AppConnection.
  public struct AppConnectionDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A BeyondCorp AppConnection in the project.
    public var appConnection: AppConnection? = nil

    /// If type=GCP_REGIONAL_MIG, contains most recent VM instances, like
    /// `https://www.googleapis.com/compute/v1/projects/{project_id}/zones/{zone_id}/instances/{instance_id}`.
    public var recentMigVms: [Swift.String] = []

    /// Initialize a new instance of `AppConnectionDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AppConnectionDetails().with { $0.appConnection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.beyondcorp.appconnections.v1.ResolveAppConnectionsResponse.AppConnectionDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.beyondcorp.appconnections.v1.ResolveAppConnectionsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [ResolveAppConnectionsResponse.AppConnectionDetails] {
    return self.appConnectionDetails
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
